spring:
  application:
    name: link-service
  cloud:
    config:
      uri: http://localhost:8888


  data:
    mongodb:
      uri: mongodb://localhost:27017/linkdb

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    appname: link-service

message:
  hello: "qwerty"

