spring:
  application:
    name: link-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/linkdb

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    appname: link-service

